# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Meizi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.8'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  # Pods for Meizi

  target 'MeiziTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeiziUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
